### ISSUE TITLE
源码编译的问题

### ISSUE THREAD

**Issue by wagayaluda** [mistzzt/Terraria-Map-Editor#1]
源码编译以后快捷键用不了了~（s p f之类的）
用的vs2015
请问这是编译器的问题还是源码的问题

**Comment by mistzzt** [comment]
经测试，Ctrl+S Ctrl+Z Ctrl+Y均可正常使用。
顺便一提，你所说的`s p f`中只有S是可用快捷键。
其他在英文原版里没有。

**Comment by wagayaluda** [comment]
那个，官方英文版编译好的确实可以用快捷键（s是select，p是point，f是fill），但这个汉化版和官方源码编译出来的版本都不能用这几个快捷键，请问是不是因为官方给的源码有问题= =
请教一下

**Comment by mistzzt** [comment]
已经确认有问题，应该是工具名称修改带来的。

英文版的release可以使用P和F快捷键；Ctrl+S是Save，保存。

**Comment by mistzzt** [comment]
已经在提交 [23ab5e4dcc](https://github.com/mistzzt/Terraria-Map-Editor/commit/23ab5e4dcc3f76b2d62ff924b22a78be65d2e01a) 中解决。
